ServerRoot "/usr/local/apache2"
Listen 80
ServerName localhost

User www-data
Group www-data

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dav_module modules/mod_dav.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule dav_lock_module modules/mod_dav_lock.so
LoadModule log_config_module modules/mod_log_config.so

LogFormat "%h %t \"%m %U\" %>s \"%{If}i\"" webdav
CustomLog /usr/local/apache2/logs/access_log webdav

DavLockDB /var/lock/davlock/DavLockDB

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    DAV On
    Require all granted
    Options Indexes
</Directory>
